version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
configuration: Release
platform: Any CPU
shallow_clone: true
before_build:
- rd "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Amazon Web Services LLC" /s /q
build:
  verbosity: normal
  
